name: DisplayNameChanger
description: DisplayNameChanger
main: com.connorlinfoot.displaynamechanger.Main
version: 2.0
author: ConnorLinfoot
website: http://connorlinfoot.com
depends: [TagAPI]
commands:
  cdn:
    description: Change the Display Name of you or another player
permissions:
  displayname.change.*:
    description: Gives access to all the DisplayNameChanger commands
    default: op
    children:
      displayname.change.self: true
      displayname.change.others: true
      displayname.change.ignore: false